name: Terraform Deploy

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    services:
      localstack:
        image: localstack/localstack:latest
        ports:
          - 4566:4566

    steps:
      - name: Checkout del repositorio
        uses: actions/checkout@v4

      - name: Configuración de Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Inicialización de Terraform
        run: terraform init

      - name: Planificación de Terraform
        run: terraform plan

      - name: Aplicación de Terraform
        run: terraform apply -auto-approve
